import ast
import re


def is_valid_call_args(function_name: str, input_value: str) -> bool:
    """Check whether the generated input is valid Python arguments."""

    try:
        ast.parse(f"{function_name}({input_value})")
        return input_value.count(",") == 1
    except SyntaxError:
        return False


def build_test_file(code: str, test_cases: list) -> str:

    match = re.search(r"def\s+(\w+)\s*\(", code)

    if not match:
        return "# Could not detect a Python function."

    function_name = match.group(1)

    output = [
        "import pytest",
        "",
        "# Generated by TestPilot AI",
        "",
        code,
        "",
    ]

    test_number = 0

    for test in test_cases:

        input_value = str(test.get("input", "")).strip()
        expected = str(test.get("expected", "")).strip()
        name = test.get("name", "generated_test")

        safe_name = re.sub(
            r"[^a-zA-Z0-9_]+",
            "_",
            name.lower()
        ).strip("_")

        # ------------------------------------------------
        # Validate function arguments
        # ------------------------------------------------

        if not is_valid_call_args(function_name, input_value):
            continue

        # ------------------------------------------------
        # Exception test
        # ------------------------------------------------

        if expected.lower().startswith("typeerror"):

            test_number += 1

            output.append(
                f"def test_{safe_name}_{test_number}():"
            )

            output.append(
                "    with pytest.raises(TypeError):"
            )

            output.append(
                f"        {function_name}({input_value})"
            )

            output.append("")

            continue

        # ------------------------------------------------
        # Normal output test
        # ------------------------------------------------

        # Ignore obviously malformed expected values
        if not expected:
            continue

        try:
            ast.parse(expected)
        except SyntaxError:
            continue

        test_number += 1

        output.append(
            f"def test_{safe_name}_{test_number}():"
        )

        output.append(
            f"    assert {function_name}({input_value}) == {expected}"
        )

        output.append("")

    return "\n".join(output)